name: Security Pipeline

on: push
  pull_request

permissions:
  contents: read

env:
  SEVERITY_THRESHOLD: medium # low|medium|high|critical
  GRACE_PERIOD_DAYS: "14" # dias de carência

jobs:
  snyk-sca:
    name: Snyk Open Source (SCA)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Snyk test (SCA) -> JSON
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p reports
          snyk test --all-projects --severity-threshold=${{ env.SEVERITY_THRESHOLD }} \
            --json-file-output=reports/snyk-sca.json || true
          snyk-to-html -i reports/snyk-sca.json -o reports/snyk-sca.html || true

      # >>> BLOQUEIA somente se issues >= threshold estiverem FORA do período de carência <<<
      - name: Grace period check (SCA)
        run: |
          set -e
          [ -f reports/snyk-sca.json ] || { echo "No SCA JSON found."; exit 0; }
          cutoff=$(date -d "-${{ env.GRACE_PERIOD_DAYS }} days" +%s)

          case "${{ env.SEVERITY_THRESHOLD }}" in
            low) thr=0;; medium) thr=1;; high) thr=2;; critical) thr=3;; *) thr=2;;
          esac

          violations=$(
            jq -r \
              --argjson cutoff "$cutoff" \
              --argjson thr "$thr" '
              def sevscore: {"low":0,"medium":1,"high":2,"critical":3}[.severity];
              # pega a primeira data disponível
              def datefield: (.introducedDate // .firstSeen // .creationTime // .disclosureTime // .publicationTime // .updated);
              [
                .vulnerabilities[]?
                | select(sevscore >= $thr)
                | . as $v
                | ( $v | datefield // "" ) as $d
                # normaliza tirando milissegundos e converte pra epoch (null se não der)
                | ($d | gsub("\\.[0-9]+Z$"; "Z") | fromdateiso8601? ) as $epoch
                | select($epoch != null and $epoch <= $cutoff)
                | {sev: $v.severity, pkg: $v.packageName, title: $v.title, date: $d}
              ]' reports/snyk-sca.json
          )

          if [ "$violations" != "[]" ]; then
            echo "::error::SCA violations beyond ${{ env.GRACE_PERIOD_DAYS }} days:"
            echo "$violations"
            exit 1
          fi
          echo "SCA OK: only new (in grace) or below threshold."

      - name: Snyk monitor (SCA) -> UI (by branch)
        if: always()
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk monitor --all-projects --target-reference="${{ github.ref_name }}" || true

      - name: Upload SCA reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca-reports
          path: reports/*sca.*

  snyk-code:
    name: Snyk Code (SAST)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Snyk Code test -> JSON/HTML (local reports)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p reports
          snyk code test --severity-threshold=${{ env.SEVERITY_THRESHOLD }} \
            --json-file-output=reports/snyk-code.json || true
          if [ -f reports/snyk-code.json ]; then
            snyk-to-html -i reports/snyk-code.json -o reports/snyk-code.html
          else
            echo "<html><body><h3>No Snyk Code issues found</h3></body></html>" > reports/snyk-code.html
          fi

      # >>> BLOQUEIA somente se issues >= threshold estiverem FORA do período de carência <<<
      - name: Grace period check (SAST)
        run: |
          set -e
          [ -f reports/snyk-code.json ] || { echo "No SAST JSON found."; exit 0; }
          cutoff=$(date -d "-${{ env.GRACE_PERIOD_DAYS }} days" +%s)

          case "${{ env.SEVERITY_THRESHOLD }}" in
            low) thr=0;; medium) thr=1;; high) thr=2;; critical) thr=3;; *) thr=2;;
          esac

          violations=$(
            jq -r \
              --argjson cutoff "$cutoff" \
              --argjson thr "$thr" '
              def sevscore: {"low":0,"medium":1,"high":2,"critical":3}[.severity];
              def datefield: (.introducedDate // .firstSeen // .creationTime // .disclosureTime // .publicationTime // .updated);
              [
                .issues[]?
                | select(sevscore >= $thr)
                | . as $i
                | ( $i | datefield // "" ) as $d
                | ($d | gsub("\\.[0-9]+Z$"; "Z") | fromdateiso8601? ) as $epoch
                | select($epoch != null and $epoch <= $cutoff)
                | {sev: $i.severity, rule: $i.ruleId, title: $i.title, date: $d}
              ]' reports/snyk-code.json
          )

          if [ "$violations" != "[]" ]; then
            echo "::error::SAST violations beyond ${{ env.GRACE_PERIOD_DAYS }} days:"
            echo "$violations"
            exit 1
          fi
          echo "SAST OK: only new (in grace) or below threshold."

      - name: Upload Code reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-reports
          path: reports/*code.*
