name: Security Pipeline

on:
  pull_request:

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"   # Regras de segurança pré-prontas
          exit-code: 0     # Não quebra o pipeline (muda pra 1 se quiser bloquear PRs)

  trivy:
    name: Run Trivy SCA + SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 0      # Não quebra o pipeline (muda pra 1 se quiser bloquear PRs)
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM
